dataset:
  test_size: 0.1
  random_state: 42

cleaning:
  min_rto_count: 21
  min_model_count: 10

transformation:
  discretize: True
  standardise: True

model:
  try_model: False
  tune_gradient_boosting: True
  tune_random_forest: True
  tune_XGBoost: True