dataset:
  test_size: 0.1
  random_state: 42

transformation:
  discretize: False
  standardise: True
  min_rto_count: 0
  min_model_count: 10

model:
  try_model: True
  tune_gradient_boosting: False
  tune_random_forest: False
  tune_XGBoost: False
  tune_light_boost: False