name: CI pipeline

on:
    push:
      branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        
        - name: set up cml
          uses: iterative/setup-cml@v2
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12
        
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: installing dataset
          run:
            python ./second_hand_car_price_prediction/bring_dataset.py
        
        - name: run pipeline
          run:
            dvc exp run
        
            # cml part . cml stands for continious machine learning
        - name: creating report
          env:
            REPO_TOKEN: ${{secrets.Github_token}}
          run: |
            python ./second_hand_car_price_prediction/generate_report.py
            cml comment create report.md